### PR TITLE
fix: use TS Config presets to transpile correctly

### LINKED ISSUE #324: Cannot use import statement outside a module
After upgrading to latest release (7.0.0), I got this error:

```
/Users/user/Desktop/project/node_modules/@jorgebodega/typeorm-seeding/dist/cli.js:2
import { bootstrap } from './commands/seed.command';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1290:20)
    at Module._compile (node:internal/modules/cjs/loader:1342:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Object.require.extensions.<computed> [as .js] (/Users/user/Desktop/project/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at phase4 (/Users/user/Desktop/project/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/Users/user/Desktop/project/node_modules/ts-node/src/bin.ts:95:10)
```

### PR DESCRIPTION
**Pull request by alumni**
Fixes #324

### CODE REVIEW

**Comment by dubems** [comment]
Thanks @alumni for making this fix.

Quick question: Is there a reason this is not merged yet?   I'm currently having the same issue referenced in this PR, i:e #324 

I'd also like to know if there is a workaround for this while this PR is not merged yet

cc: @jorgebodega

**Comment by jorgebodega** [comment]
I'm going to try to create a new PR with some changes of this one and some other changes, and merge this weekend.

And probably, those changes are going to be ported to https://github.com/jorgebodega/typeorm-factory as well

**Comment by jorgebodega** [comment]
Please, try the new version [7.1.0-next.1](https://www.npmjs.com/package/@jorgebodega/typeorm-seeding/v/7.1.0-next.1) and check if that works for all of you. If not, please comment here and we can try to find the solution together.

**Comment by alumni** [comment]
I'm getting this:
```
> ts-node -P ./tsconfig.json -r tsconfig-paths/register -T node_modules/@jorgebodega/typeorm-seeding/dist/cli.js xxx.seed.ts --dataSource ormconfig.ts
SeederImportationError: Could not load default seeders!
    at Command.run (/yyy/node_modules/.pnpm/@jorgebodega+typeorm-seeding@7.1.0-next.1_typeorm@0.3.20/node_modules/@jorgebodega/typeorm-seeding/src/commands/seed.command.ts:42:9)
    at async Command.parseAsync (/yyy/node_modules/.pnpm/commander@12.1.0/node_modules/commander/lib/command.js:1092:5)
    at async bootstrap (/yyy/node_modules/.pnpm/@jorgebodega+typeorm-seeding@7.1.0-next.1_typeorm@0.3.20/node_modules/@jorgebodega/typeorm-seeding/src/commands/seed.command.ts:79:2) {
  [cause]: TypeError: Unknown file extension ".ts" for /yyy/xxx.seed.ts
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
      at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
      at defaultLoad (node:internal/modules/esm/load:143:22)
      at async ModuleLoader.load (node:internal/modules/esm/loader:396:7)
      at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:45)
      at async link (node:internal/modules/esm/module_job:78:21) {
    code: 'ERR_UNKNOWN_FILE_EXTENSION'
  }
}
```

**Comment by jorgebodega** [comment]
Can you give more information or create a minimal reproduction of the error?

**Comment by alumni** [comment]
@jorgebodega The issue that I see is in `commandUtils.ts`: `loadDataSource` is able to load `ormconfig.ts` correctly, but `loadSeeders` fails due to the dynamic import that is trying to load a typescript file, and somehow `ts-node` doesn't do anything about it.

In v6, the dynamic import was transpiled to a require which seemed to work, not sure why one works and the other not.

I'll try to investigate a bit more.

**Comment by alumni** [comment]
I will close this PR since this was fixed already in the `main` branch.

The issue that remains is that NodeJS can't dynamically import CommonJS modules (it's what `loadSeeders` is trying to do). This won't be fixed with a `tsconfig` option if we want to fix it for everybody.

TypeORM itself is using a utility function for supporting any kind of import: `importOrRequireFile` (in `util/ImportUtils.ts`).

**Pull request closed without merging**
